# application.yml
redis:
  host: localhost
  port: 6379

server:
  port: 8080
  # servlet:
  #   context-path: /microcom

spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 175.178.212.207:8848
        ip: 175.178.212.207
        port: 8081
        username: nacos
        password: nacos
        namespace: 346d5bf4-17af-4346-8aae-f12ce48ea903
        group: DEFAULT_GROUP
    gateway:
      discovery:
        locator:
          enabled: true
          # 是否使用service-id的小写，默认是大写
          lower-case-service-id: true
  servlet:
    multipart:
      max-file-size: 10MB        # 设置单个文件最大大小为10MB
      max-request-size: 100MB    # 设置多个文件大小为100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.178.212.207:3306/microcom?serverTimezone=Asia/Shanghai
    username: microcom
    password: muzuki2002
  redis:
    host: 175.178.212.207
    port: 6379
    password: muzuki2002
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 1
    lectuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

qcloud:
  #初始化用户身份信息 前往控制台密钥管理查看
  secretId: "AKIDEMK7j8LK4Zqwc4GPL2Xq01qQlslQxX1J"
  secretKey: "AC4mOq9JRPAmEYs36zsZ3NYZMUXN0Sn2"
  # 指定要上传到的存储桶
  bucketName: "mu-1310320682"
  # 地区选择
  regionName: "ap-guangzhou"

meilisearch:
  host-url: http://localhost:7700
  api-key: k0AiJ9urNCLA7DoKKZLw1MZXxkDiDkyzwsJoNjMKtkc

justauth:
  cache:
    type: redis
    # 缓存前缀，目前只对redis缓存生效，默认 JUSTAUTH::STATE::
    prefix: ''
    # 超时时长，目前只对redis缓存生效，默认3分钟
    timeout: 1h
  enabled: true
  type:
    GITHUB:
      client-id: f5ac19dd3d2c51884dde
      client-secret: e71624531c93720a08f69acbbf8c924081a2ce4d
      redirect-uri: http://localhost:8080/microcom/oauth/github/callback
    DINGTALK:
      client-id: dingexis9lxwy68c18qv
      client-secret: bGTWH6LqhNNNp3wSw1Jk55Pt8LmD5DHiexeU4Yl01Da0c6PvV5wfUphLf3-IvHqx
      redirect-uri: http://localhost:8080/microcom/oauth/dingtalk/callback

