# application.yml
redis:
  host: localhost
  port: 6379

server:
  port: 8080
  servlet:
    context-path: /microcom

meilisearch:
  host-url: http://localhost:7700
  api-key: k0AiJ9urNCLA7DoKKZLw1MZXxkDiDkyzwsJoNjMKtkc

spring:
  application:
    name: mybatis-plus-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai
    username: root
    password: muzuki
  redis:
    host: localhost
    port: 6379
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 1
    lectuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印

justauth:
  cache:
    type: redis
    # 缓存前缀，目前只对redis缓存生效，默认 JUSTAUTH::STATE::
    prefix: ''
    # 超时时长，目前只对redis缓存生效，默认3分钟
    timeout: 1h
  enabled: true
  type:
    GITHUB:
      client-id: f5ac19dd3d2c51884dde
      client-secret: e71624531c93720a08f69acbbf8c924081a2ce4d
      redirect-uri: http://localhost:8080/blog/oauth/github/callback
    DINGTALK:
      client-id: dingexis9lxwy68c18qv
      client-secret: bGTWH6LqhNNNp3wSw1Jk55Pt8LmD5DHiexeU4Yl01Da0c6PvV5wfUphLf3-IvHqx
      redirect-uri: http://localhost:8080/blog/oauth/dingtalk/callback

